//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Development\CodeGenie\src\CodeGenie.Core\ANTLR\CodeGenie.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CodeGenieParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICodeGenieVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.componentDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentDefinition([NotNull] CodeGenieParser.ComponentDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent([NotNull] CodeGenieParser.ComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.component_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_type([NotNull] CodeGenieParser.Component_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.component_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_details([NotNull] CodeGenieParser.Component_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTags([NotNull] CodeGenieParser.TagsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] CodeGenieParser.TagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.purpose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurpose([NotNull] CodeGenieParser.PurposeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] CodeGenieParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] CodeGenieParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.attribute_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_details([NotNull] CodeGenieParser.Attribute_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.methods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethods([NotNull] CodeGenieParser.MethodsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] CodeGenieParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] CodeGenieParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.method_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_details([NotNull] CodeGenieParser.Method_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.relationships"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationships([NotNull] CodeGenieParser.RelationshipsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.relationship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationship([NotNull] CodeGenieParser.RelationshipContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.cardinality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardinality([NotNull] CodeGenieParser.CardinalityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.cardinality_count"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCardinality_count([NotNull] CodeGenieParser.Cardinality_countContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependency([NotNull] CodeGenieParser.DependencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.dependency_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependency_details([NotNull] CodeGenieParser.Dependency_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.composes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposes([NotNull] CodeGenieParser.ComposesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.composes_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposes_details([NotNull] CodeGenieParser.Composes_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.aggregates"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregates([NotNull] CodeGenieParser.AggregatesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.aggregates_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregates_details([NotNull] CodeGenieParser.Aggregates_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.realizes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealizes([NotNull] CodeGenieParser.RealizesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.realizes_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealizes_details([NotNull] CodeGenieParser.Realizes_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.specializes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecializes([NotNull] CodeGenieParser.SpecializesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.specializes_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecializes_details([NotNull] CodeGenieParser.Specializes_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.access_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_scope([NotNull] CodeGenieParser.Access_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] CodeGenieParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CodeGenieParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CodeGenieParser.TypeContext context);
}
